name: Publish Release

on:
  push:
    branches: [ "master" ]

jobs:
  push_release_to_registry:
    name: Push release image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push 86_64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            cachyos/docker-makepkg:x86_64
            cachyos/docker-makepkg:latest
          build-args: |
            ARCH=x86_64
          platforms: linux/amd64/v2
          
      - name: Build and push x86_64_v3 image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            cachyos/docker-makepkg:x86_64_v3
          build-args: |
            ARCH=x86_64_v3
          platforms: linux/amd64/v3
          
      - name: Build and push x86_64_v4 image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            cachyos/docker-makepkg:x86_64_v4
          build-args: |
            ARCH=x86_64_v4
          platforms: linux/amd64/v4
          
      - name: Build and push x86_64_znver4 image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            cachyos/docker-makepkg:x86_64_znver4
          build-args: |
            ARCH=x86_64_znver4
          platforms: linux/amd64/v4