name: Publish Release

on:
  release:
    types: [published]

jobs:
  push_release_to_registry:
    name: Push release image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push release image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tenasi/docker-makepkg:x86_64
            tenasi/docker-makepkg:latest
          build-args: |
            x86_64
          
      - name: Build and push release image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tenasi/docker-makepkg_v3:x86_64_v3
          build-args: |
            x86_64_v3
          
      - name: Build and push release image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tenasi/docker-makepkg:x86_64_v4
          build-args: |
            x86_64_v4
          
      - name: Build and push release image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tenasi/docker-makepkg:x86_64_znver4
          build-args: |
            x86_64_znver4